# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: service-bot_development
  pool: 5
  username: "chenhuang"
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: service-bot_test
  pool: 5
  username: "chenhuang"
  password:
